# Generated by Django 6.0.2 on 2026-02-07 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_snippet', models.TextField(max_length=200, verbose_name='Мәтін үзіндісі')),
                ('language', models.CharField(choices=[('auto', 'Авто анықтау'), ('kk', 'Қазақша'), ('ru', 'Орысша')], default='auto', max_length=10, verbose_name='Тіл')),
                ('primary_emotion', models.CharField(max_length=50, verbose_name='Негізгі эмоция')),
                ('confidence', models.FloatField(verbose_name='Сенімділік')),
                ('probabilities', models.JSONField(verbose_name='Ықтималдылар')),
                ('sentence_count', models.IntegerField(default=0, verbose_name='Сөйлем саны')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Құрылған уақыт')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='Сессия кілті')),
            ],
            options={
                'verbose_name': 'Талдау тарихы',
                'verbose_name_plural': 'Талдау тарихы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmotionModelInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Модель атауы')),
                ('description', models.TextField(verbose_name='Сипаттама')),
                ('emotions', models.JSONField(verbose_name='Эмоциялар тізімі')),
                ('limitations', models.TextField(verbose_name='Шектеулер')),
                ('is_active', models.BooleanField(default=True, verbose_name='Белсенді')),
            ],
            options={
                'verbose_name': 'Модель ақпараты',
                'verbose_name_plural': 'Модель ақпараты',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('positive', '👍 Дұрыс'), ('negative', '👎 Қате')], max_length=10, verbose_name='Кері байланыс түрі')),
                ('comment', models.TextField(blank=True, verbose_name='Пікір')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Құрылған уақыт')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='analyzer.analysishistory', verbose_name='Талдау')),
            ],
            options={
                'verbose_name': 'Кері байланыс',
                'verbose_name_plural': 'Кері байланыс',
            },
        ),
    ]
